# Maintainer: Israel Dahl <israeldahl@protonmail.com>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=creature_fighter-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="A creature fighter math game written in Rust + FLTK"
url="https://github.com/1sra3l/creature_math_fighter"
license=("GPL3")
arch=("x86_64")
provides=("creature_fighter")
conflicts=("creature_fighter")
source=("https://github.com/1sra3l/creature_math_fighter/releases/download/v$pkgver/creature_fighter-$pkgver-x86_64.tar.gz")
sha256sums=("e0c75f8069228ee941a3fc259b206b57fc72d135fdccfec6012e50d00a47aa1d")

package() {
    install -Dm755 creature_fighter -t "$pkgdir/usr/bin"
}
